In [1]:
import numpy as np


Creating a matrix using numpy

In [4]:
matrix_1 = np.array([[1,2,3,4],[5,6,7,8]])
matrix_1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
matrix_1.shape

(2, 4)

creating matrices with random values

In [8]:
random_matrix = np.random.rand(3,4)
random_matrix

array([[0.21356797, 0.16297916, 0.77203096, 0.58942408],
       [0.77733229, 0.45732383, 0.25617339, 0.13177589],
       [0.70253594, 0.93875612, 0.19672995, 0.48943963]])

In [11]:
# crating the matrix with random integer
random_matrix = np.random.randint(100,size=(3,4))
random_matrix

array([[20, 61, 84, 10],
       [70, 57, 99, 25],
       [ 0, 73,  0, 10]])

MAtrix with all the values as 1

In [13]:
matrix= np.ones((3,4))
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
matrix= np.ones((3,4),dtype=int)
matrix

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

null matrix or zeros matrix

In [18]:
null_matrix= np.zeros((3,4),dtype=int)
null_matrix

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

identity matrix

In [20]:
id_matx= np.eye(5,dtype=int)
id_matx

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

transpose of matrix

In [21]:
# crating the matrix with random integer
random_matrix = np.random.randint(100,size=(3,4))
random_matrix

array([[22,  3, 56, 60],
       [47, 43, 69, 62],
       [12,  8, 64, 71]])

In [22]:
random_matrix.T

array([[22, 47, 12],
       [ 3, 43,  8],
       [56, 69, 64],
       [60, 62, 71]])

In [23]:
np.transpose(random_matrix)

array([[22, 47, 12],
       [ 3, 43,  8],
       [56, 69, 64],
       [60, 62, 71]])

maths of matrix

In [30]:
# matrix addition

a=np.array([[2,4],[2,6]])
b=np.array([[5,6],[3,4]])

np.add(a,b)

array([[ 7, 10],
       [ 5, 10]])

In [31]:
# crating the matrix with random integer
random_matrix_1 = np.random.randint(100,size=(3,4))
random_matrix_2 = np.random.randint(100,size=(3,4))
print(random_matrix_1)
print(random_matrix_2)

[[55 46 40  0]
 [52 89 65 95]
 [ 8 19 55 10]]
[[45 16 47 75]
 [70 53 54 21]
 [73 84 89 30]]


In [32]:
np.add(random_matrix_1,random_matrix_2)

array([[100,  62,  87,  75],
       [122, 142, 119, 116],
       [ 81, 103, 144,  40]])

In [33]:
random_matrix_1 = np.random.randint(100,size=(3,3))  # see i change the value of the column
random_matrix_2 = np.random.randint(100,size=(3,4))
print(random_matrix_1)
print(random_matrix_2)

[[73 56 11]
 [13 28 75]
 [12 20 33]]
[[91 76 43 60]
 [74 83 33 14]
 [89 58 55 46]]


In [34]:
np.add(random_matrix_1,random_matrix_2)

ValueError: ignored

matrix suntraction

In [35]:
# crating the matrix with random integer
random_matrix_1 = np.random.randint(100,size=(3,4))
random_matrix_2 = np.random.randint(100,size=(3,4))
print(random_matrix_1)
print(random_matrix_2)

[[43 88 61 22]
 [81  5 96 41]
 [32 97 61 60]]
[[95 77 93  3]
 [ 6  3 92 75]
 [22 63 31 82]]


In [36]:
np.subtract(random_matrix_1,random_matrix_2)

array([[-52,  11, -32,  19],
       [ 75,   2,   4, -34],
       [ 10,  34,  30, -22]])

mutiplying a matrix with scalar

In [37]:
x=5
y=np.array([[1,2,3],[4,5,6]])


In [38]:
np.multiply(x,y)

array([[ 5, 10, 15],
       [20, 25, 30]])

multiply the 2 matrix

In [39]:
# crating the matrix with random integer
random_matrix_1 = np.random.randint(100,size=(3,4))
random_matrix_2 = np.random.randint(100,size=(3,4))
print(random_matrix_1)
print(random_matrix_2)

[[28 70 34 62]
 [96 83 93 75]
 [94  1  2 71]]
[[45 82 24 96]
 [25 53 47  6]
 [41 20 21 79]]


In [40]:
np.multiply(random_matrix_1,random_matrix_2)

array([[1260, 5740,  816, 5952],
       [2400, 4399, 4371,  450],
       [3854,   20,   42, 5609]])

In [44]:
 # crating the matrix with random integer
random_matrix_1 = np.random.randint(100,size=(3,5))  # see i change the value
random_matrix_2 = np.random.randint(100,size=(3,4))
print(random_matrix_1)
print(random_matrix_2)

[[34 45 82 64 53]
 [70 54 76 65 80]
 [91 29 96 98 70]]
[[76  2 16 92]
 [83 66 24  6]
 [37 74 82 20]]


In [45]:
np.multiply(random_matrix_1,random_matrix_2)

ValueError: ignored